services:
  frontend:
    build: .
    restart: always
    ports:
      - 3100:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M