name: CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Pull and Run Docker Images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEVELOP_HOST }}
          username: ${{ secrets.SSH_DEVELOP_USER }}
          password: ${{ secrets.SSH_DEVELOP_PASSWORD }}
          port: ${{ secrets.SSH_DEVELOP_PORT }}
          script: |
            cd ~/geevex-front-end-admin
            git pull
            sudo docker compose -f docker-compose.yml up -d --build
